# Use an official Maven image as a parent image
FROM maven:3.8-openjdk-11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the pom.xml file into the container at /app
COPY pom.xml /app/

# Download the project dependencies specified in the pom.xml
RUN mvn dependency:resolve

# Copy the rest of the application's source code into the container
COPY src /app/src

# Command to run unit tests using Maven
CMD ["mvn", "test"]